Refactoring user creation
aspgems/docker-dev-base-ruby pull request #1
Opened 2017-05-18 07:18 UTC by barrerajl

Motivation:
Some minor errors were shown in the console when creating an image from the actual image.

Refactor:
Move user setup logic to the shell script.
Move variables to be grouped. Also, because they are needed by the copied script, they are moved to the main image.
Also changed USER_NAME from a DEV to a VAR so, it can be changed if wanted to.

2017-05-18 07:20 UTC, eLafo approved these changes

2017-05-18 13:07 UTC, zjuanma requested changes

2017-05-18 13:07 UTC, zjuanma commented on Dockerfile
> +ARG USER_NAME=dev
Tras la experiencia en otros proyectos parametrizar el USER_NAME no aporta nada, solo complejidad a los scripts.

2017-05-18 13:07 UTC, zjuanma commented on Dockerfile
>  ENV APP_HOME=$USER_HOME/app
¿Por qué no se cuelga la aplicación directamente desde el $HOME?, no aporta nada que la aplicacion esté en $HOME/app

2017-05-18 13:07 UTC, zjuanma commented on setup_user.sh
> +mkdir -p $SSH_PATH && echo "StrictHostKeyChecking no" > $SSH_PATH/config
En lugar de hacer esto, se puede compartir el ssh_agent de la maquina host y así no tener problemas ni con ssh, ni con git, etc....

2017-05-18 14:04 UTC, barrerajl commented on setup_user.sh
> +mkdir -p $SSH_PATH && echo "StrictHostKeyChecking no" > $SSH_PATH/config
Esto es sólo si no se comparte esa parte. Que tengas la posibilidad de usar git

2017-05-18 14:05 UTC, barrerajl commented on Dockerfile
> +ARG USER_NAME=dev
Esto no hace nada si no quieres usarlo, depende de ti cambiar el valor por defecto.

2017-05-18 14:05 UTC, barrerajl commented on Dockerfile
>  ENV APP_HOME=$USER_HOME/app
si montas la aplicacion sobre home, te quedas son las carpetas ocultas de un sistema linux normal como el .ssh para ese usuario

2017-05-18 14:17 UTC, zjuanma commented on Dockerfile
> +ARG USER_NAME=dev
no veo a dev como un nombre muy apropiado, se puede confundir con /dev por ejemplo

2017-05-18 14:18 UTC, zjuanma commented on Dockerfile
>  ENV APP_HOME=$USER_HOME/app
¿para que quiero esa carpeta?
aun así, este cometario lo puedo aceptar.

2017-05-18 14:19 UTC, zjuanma commented on setup_user.sh
> +mkdir -p $SSH_PATH && echo "StrictHostKeyChecking no" > $SSH_PATH/config
no entiendo el comentario.

2017-05-18 14:31 UTC, eLafo commented on Dockerfile
>  ENV APP_HOME=$USER_HOME/app
@zjuanma porque esto es una imagen para desarrollo y necesitas tener configuraciones locales de desarrollo (para bundler, por ejemplo)

2017-05-22 08:22 UTC, barrerajl commented on Dockerfile
> +ARG USER_NAME=dev
Correcto, qué propones?

2017-05-22 08:23 UTC, barrerajl commented on setup_user.sh
> +mkdir -p $SSH_PATH && echo "StrictHostKeyChecking no" > $SSH_PATH/config
Que ambas cosas son "complementarias"

2017-05-22 09:03 UTC, zjuanma approved these changes

2017-05-22 09:07 UTC, sergiogomez approved these changes
👍

2017-05-22 10:27 UTC, merged